APP_NAME = "AFSIM Comms Inspector"

MAIN_DISPLAY = "main-display"
DISPLAYED_DATA = "displayed-data"
FILTER_MEMORY = "filter-memory"
DISPLAY_MEMORY = "display-memory"

GLOBE_GRAPH = "globe-graph"
PLOT_FILTERS = "plot-filters"

PLOTS_AREA = "plots-area"
PLOT_OPTIONS = "plot-options"
BAR_GRAPH = "bar-graph"
SUBPLOT_CATEGORY = "subplot-category"
BAR_GRAPH_CATEGORY = "bar-graph-category"
BAR_STACK_CATEGORY = "bar-stack-category"
NETWORK_LAYOUT = "network-layout"

OPTIONS_ROW = "options-row"
TIME_LABEL = "time-label"
TIME_SLIDER = "time-slider"
PREVIOUS_TIME = "previous-time"
NEXT_TIME = "next-time"
RADIOS = "radios"

EVENT_TYPE = "event-type"
MSG_SERIAL_NUMBER = "msg-serial-number"
MSG_ORIGINATOR = "msg-originator"
MSG_TYPE = "msg-type"
SENDER_NAME = "sender-name"
SENDER_TYPE = "sender-type"
SENDER_BASETYPE = "sender-basetype"
SENDER_PART = "sender-part"
SENDER_PART_TYPE = "sender-part-type"
SENDER_PART_BASETYPE = "sender-part-basetype"
RECEIVER_NAME = "receiver-name"
RECEIVER_TYPE = "receiver-type"
RECEIVER_BASETYPE = "receiver-basetype"
RECEIVER_PART = "receiver-part"
RECEIVER_PART_TYPE = "receiver-part-type"
RECEIVER_PART_BASETYPE = "receiver-part-basetype"